name: CloudSim SJF Scheduler CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Use the latest version of checkout action
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3  # Use the latest version of setup-java action
      with:
        java-version: '21'         # Specify Java 21
        distribution: 'temurin'    # Corrected spelling of Temurin (Eclipse Temurin)
        cache: maven               # Cache Maven dependencies for faster builds
    
    - name: Build with Maven
      run: mvn clean install -DskipTests && mvn clean package -DskipTests
    
    - name: Run SJF Scheduler
      run: mvn exec:java -pl modules/cloudsim-examples/ -Dexec.mainClass="org.cloudbus.cloudsim.examples.SJF_Scheduler"